<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="LogMessage" Id="{a2c69cf0-3e79-41ba-8953-14e7b1da7c83}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION LogMessage : BOOL
VAR_INPUT
	sLogMessage		: STRING[255];			// String size set to 255, default is 80
	eType			: E_MessageType;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// ADSLOG_MSGTYPE_HINT: Message type is hint.
// ADSLOG_MSGTYPE_WARN: Message type is warning.
// ADSLOG_MSGTYPE_ERROR: Message type is error.
// ADSLOG_MSGTYPE_LOG: Message is written into the LOG.
// ADSLOG_MSGTYPE_MSGBOX: Message is output to a message box. Caution: This functionality is not available under Windows CE.
// ADSLOG_MSGTYPE_STRING: Message is a directly given STRING (default).

ADSLOGSTR(eType OR ADSLOG_MSGTYPE_LOG, sLogMessage, '');]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>